### ISSUE TITLE
 Registering a new user fall in error

### ISSUE THREAD

**Issue by ins4n333** [mobsoftware/mobsocial#24]
Hi!
 "Registering a new user" fall in error
Object reference not set to an instance of an object.

   at mobSocial.Services.Emails.EmailSender.SendUserRegisteredMessage(User user, Boolean withAdmin) in C:\git\mobsocial\Libraries\mobSocial.Services\Emails\EmailSender.cs:line 83
   at mobSocial.WebApi.Controllers.AuthenticationController.Register(RegisterModel registerModel) in C:\git\mobsocial\Presentation\mobSocial.WebApi\Controllers\AuthenticationController.cs:line 152
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by wittyansh** [comment]
Hi, Please download the latest code. The issue was fixed in 68c4e4a78005b9a020599777c9188d4e62640bb4
